---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)

nyc_food_inspect = read_csv("./data/DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz")

set.seed(1)

nyc_food_inspect_smaller = 
  nyc_food_inspect %>% 
  select(cuisine_description, dba, score, zipcode, boro) %>% 
  na.omit() %>% 
  sample_n(5000)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Box Plot: Food Inspection Score by Borough

```{r}
nyc_food_inspect_smaller%>% 
  plot_ly(y = ~score, color = ~boro, type = "box",
          colors = "Set2")
```

Column {data-width=350}
-----------------------------------------------------------------------


### Bar Chart: Top 10 Common Restaurant Types in NYC

```{r}
nyc_food_inspect_smaller %>% 
  count(cuisine_description) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar", showlegend = FALSE)

```


### Violin Plot: Food Inspection Score by Borough

```{r}
scatter_ggplot = 
  nyc_food_inspect_smaller %>% 
  ggplot(aes(x = boro, y = score)) + 
  geom_violin(aes(fill = boro), color = "blue", alpha = .5) + 
  theme_classic()

ggplotly(scatter_ggplot)
```